Repository jfrog/frogbot, pull requests merged in 2022-08, with the labels that each got.

#120 Add missing authentication to remote.List method
  commands/createfixpullrequests.go
  commands/utils/git.go
Labels: bug, safe to test

#121 Improve fix version selection logic
  commands/createfixpullrequests.go
Labels: improvement

#122 Change starter-workflows naming
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  starter-workflows/README.md
  starter-workflows/code-scanning/frogbot-scan-and-fix.yml
  starter-workflows/code-scanning/frogbot-scan-pr.yml
  starter-workflows/code-scanning/properties/frogbot-scan-and-fix.properties.json
  starter-workflows/code-scanning/properties/frogbot-scan-pr.properties.json
  templates/github-actions/README.md
  templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
  templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
  templates/github-actions/scan-pull-request/frogbot-scan-pr-dotnet.yml
  templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml
  templates/github-actions/scan-pull-request/frogbot-scan-pr-gradle.yml
  templates/github-actions/scan-pull-request/frogbot-scan-pr-maven.yml
  templates/github-actions/scan-pull-request/frogbot-scan-pr-npm.yml
  templates/github-actions/scan-pull-request/frogbot-scan-pr-nuget.yml
  templates/github-actions/scan-pull-request/frogbot-scan-pr-pip.yml
  templates/github-actions/scan-pull-request/frogbot-scan-pr-pipenv.yml
Labels: safe to test, improvement

#107 Added GitHub security tab in createfixpullrequests
  .github/workflows/test.yml
  README.md
  action/node_modules/.package-lock.json
  action/package-lock.json
  action/package.json
  commands/createfixpullrequests.go
  commands/utils/params.go
  commands/utils/utils.go
  go.mod
  go.sum
  img.png
  img_1.png
Labels: new feature

#128 Fix compilation
  .github/workflows/test.yml
  go.mod
  go.sum
Labels: safe to test, ignore for release

#129 Fix dependencies
  go.mod
  go.sum
Labels: safe to test, ignore for release

#131 Update froggit-go version
  go.mod
  go.sum
Labels: safe to test, ignore for release

#130 Update test.yml pip/pipenv install
  .github/workflows/test.yml
Labels: safe to test, ignore for release

#133 Update readme and templates
  README.md
  images/github-code-scanning.png
  img.png
  starter-workflows/code-scanning/frogbot-scan-and-fix.yml
  starter-workflows/code-scanning/frogbot-scan-pr.yml
  templates/github-actions/README.md
  templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
  templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
  templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
  templates/github-actions/scan-pull-request/frogbot-scan-pr-yarn.yml
Labels: ignore for release

#136 Fix Scan and Fix issue for Go + README edit
  README.md
  commands/createfixpullrequests.go
  commands/utils/utils.go
Labels: bug, safe to test

#138 Ignore .jfrog config when running audit command
  commands/scanpullrequest.go
  go.mod
  go.sum
  templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml
Labels: bug, safe to test

#141 Add static analysis check and update go 1.18
  .github/workflows/analysis.yml
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/test.yml
  commands/testdata/projects/go/go.mod
  go.mod
  go.sum
  release/pipelines.yml
  starter-workflows/code-scanning/frogbot-scan-and-fix.yml
  starter-workflows/code-scanning/frogbot-scan-pr.yml
Labels: ignore for release
