Repository jfrog/frogbot, pull requests merged in 2022-07, with the labels that each got.

#93 Fix bitbucket server git provider name
  README.md
  commands/utils/consts.go
  commands/utils/params.go
  commands/utils/params_test.go
Labels: safe to test

#98 Added Frogbot support for viewing all of the vulnerabilities + Updated Frogbot images
  .github/release.yml
  .github/workflows/frogbot-pull-request.yml
  .github/workflows/test.yml
  commands/scanpullrequest.go
  commands/scanpullrequest_test.go
  commands/utils/consts.go
  commands/utils/params.go
  images/frogbot-intro.png
  resources/noVulnerabilityBanner.png
  resources/vulnerabilitiesBanner.png
  templates/github-actions/scan-pull-request/frogbot-scan-pr-dotnet.yml
  templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml
  templates/github-actions/scan-pull-request/frogbot-scan-pr-gradle.yml
  templates/github-actions/scan-pull-request/frogbot-scan-pr-maven.yml
  templates/github-actions/scan-pull-request/frogbot-scan-pr-npm.yml
  templates/github-actions/scan-pull-request/frogbot-scan-pr-nuget.yml
  templates/github-actions/scan-pull-request/frogbot-scan-pr-pip.yml
  templates/github-actions/scan-pull-request/frogbot-scan-pr-pipenv.yml
Labels: safe to test, new feature

#103 Cleanup README
  .github/workflows/test.yml
  README.md
Labels: safe to test

#108 Fix to GitLab's documentation
  README.md
  commands/commands.go
  commands/createfixpullrequests.go
Labels: bug

#104 Add Frogbot to Github Templates
  starter-workflows/README.md
  starter-workflows/code-scanning/frogbot-fix.yml
  starter-workflows/code-scanning/frogbot-scan-pr.yml
  starter-workflows/code-scanning/properties/frogbot-fix.properties.json
  starter-workflows/code-scanning/properties/frogbot-scan-pr.properties.json
  starter-workflows/icons/frogbot.svg
Labels: new feature

#112 Create PR Fixes in Temp Directory
  commands/createfixpullrequests.go
  commands/utils/git.go
Labels: safe to test, improvement

#114 Upgrade Dependencies
  commands/scanpullrequest.go
  go.mod
  go.sum
Labels: safe to test, dependencies
