Repository jfrog/frogbot, pull requests merged in 2022-10, with the labels that each got.

#154 Improve logs and scan multiple PRs aggregate errors
  commands/scanpullrequest.go
  commands/scanpullrequests.go
  go.mod
  go.sum
Labels: improvement

#156 Add new bug report view
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: ignore for release

#172 Update dependencies
  action/package-lock.json
Labels: improvement

#173 Update Poetry tests
  .github/workflows/test.yml
Labels: ignore for release

#169 Fix Scan Results Comparison for Multi Modules Projects
  commands/scanpullrequest.go
  commands/scanpullrequest_test.go
  go.mod
  go.sum
Labels: bug

#174 Fix Poetry test
  commands/testdata/projects/poetry/pyproject.toml
Labels: ignore for release
