Repository jfrog/frogbot, pull requests merged in 2022-12, with the labels that each got.

#189 Add the required permissions to the Frogbot config files used to scan this repo
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
Labels: ignore for release

#195 Update Frogbot dependencies
  go.mod
  go.sum
Labels: dependencies

#188 Add scan-pull-requests command for GitHub Actions
  action/src/main.ts
  action/src/utils.ts
  docs/templates/github-actions/scan-pull-requests/frogbot-scan-pull-requests.yml
Labels: improvement

#196 Support Azure Repos VCS
  commands/createfixpullrequests_test.go
  commands/utils/consts.go
  commands/utils/git.go
  commands/utils/params.go
  commands/utils/params_test.go
  go.mod
  go.sum
Labels: new feature

#202 Add Logger to VCS client
  commands/utils/params.go
  go.mod
  go.sum
Labels: improvement

#206 Fix duplicate working dirs when with scan-pull-requests
  commands/scanpullrequests.go
Labels: bug

#205 Remove emojis from pull request comment in Bitbucket Server
  commands/scanpullrequest.go
  commands/scanpullrequests_test.go
  commands/utils/icons.go
  commands/utils/icons_test.go
Labels: bug

#208 Bug Fix - vulnerability fix version suggested downgrading the current version
  commands/createfixpullrequests.go
  commands/createfixpullrequests_test.go
Labels: bug

#210 fix TestScanAllPullRequestsMultiRepo
  commands/scanpullrequests_test.go
Labels: ignore for release

#191 Docs Improvements - Add azure repos
  README.md
  docs/install-azure-repos.md
  docs/install-bitbucket-server.md
  docs/templates/github-actions/README.md
  go.mod
  go.sum
  images/azure-branch-policies.png
  images/azure-branches.png
  images/azure-build-policy.png
  images/azure-build-validation.png
  images/azure-new-pipeline.png
  images/azure-new-variable.png
  images/azure-select-repo-to-test.png
  images/azure-set-code-source.png
  images/azure-starter-pipeline.png
  images/azure-variables-button.png
Labels: ignore for release

#197 Restructure documentation
  README.md
  docs/frogbot-config.md
  docs/install-azure-repos.md
  docs/install-bitbucket-server.md
  docs/install-github.md
  docs/templates/.frogbot/frogbot-config.yml
  docs/templates/github-actions/README.md
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-dotnet.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-gradle.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-maven.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-npm.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-nuget.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pip.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pipenv.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-yarn.yml
  docs/templates/github-actions/scan-pull-requests/frogbot-scan-pull-requests.yml
Labels: ignore for release

#204 Add scan and fix repos command
  action/src/main.ts
  action/src/utils.ts
  commands/commands.go
  commands/createfixpullrequests.go
  commands/scanandfixrepos.go
  commands/scanandfixrepos_test.go
  commands/scanpullrequest.go
  commands/scanpullrequest_test.go
  commands/scanpullrequests.go
  commands/scanpullrequests_test.go
  commands/testdata/config/frogbot-config-clean-test-proj.yml
  commands/testdata/config/frogbot-config-multi-dir-test-proj.yml
  commands/testdata/config/frogbot-config-scan-and-fix-repos.yml
  commands/testdata/config/frogbot-config-test-params.yml
  commands/testdata/config/frogbot-config-test-proj-subdir.yml
  commands/testdata/config/frogbot-config-test-proj.yml
  commands/testdata/scanandfixrepos/mvn-repo/pom.xml
  commands/testdata/scanandfixrepos/npm-repo/package-lock.json
  commands/testdata/scanandfixrepos/npm-repo/package.json
  commands/testdata/scanandfixrepos/pip-repo/requirements.txt
  commands/utils/consts.go
  commands/utils/git.go
  commands/utils/icons.go
  commands/utils/params.go
  commands/utils/params_test.go
  commands/utils/testsutils.go
  commands/utils/utils.go
  go.mod
Labels: new feature

#211 Add .frogbot/frogbot-config.yml
  .frogbot/frogbot-config.yml
  .github/workflows/frogbot-scan-pr.yml
  README.md
Labels: ignore for release

#213 Add .frogbot/frogbot-config.yml
  .frogbot/frogbot-config.yml
  action/node_modules/.package-lock.json
  commands/utils/params_test.go
Labels: ignore for release

#214 align dev with master
  .frogbot/frogbot-config.yml
  .github/workflows/frogbot-scan-pr.yml
  README.md
  action/node_modules/.package-lock.json
  commands/utils/params_test.go
Labels: ignore for release

#216 change config + fix action bug
  .frogbot/frogbot-config.yml
  action/package-lock.json
Labels: ignore for release

#217 Documentation corrections
  README.md
  docs/install-github.md
  docs/templates/.frogbot/frogbot-config.yml
  docs/templates/github-actions/README.md
Labels: ignore for release
