Repository jfrog/frogbot, pull requests merged in 2023-08, with the labels that each got.

#408 Improve GetUniqueID
  commands/createfixpullrequests_test.go
  commands/utils/utils.go
  commands/utils/utils_test.go
  go.mod
  go.sum
Labels: improvement

#409 Update to the workflows docs
  .github/workflows/frogbot-scan-and-fix.yml
  docs/install-azure-repos.md
  docs/install-bitbucket-server.md
  docs/install-github.md
  docs/install-gitlab.md
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-dotnet.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-gradle.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-maven.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-npm.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-nuget.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pip.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pipenv.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-poetry.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-yarn.yml
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
  starter-workflows/code-scanning/frogbot-scan-and-fix.yml
  starter-workflows/code-scanning/frogbot-scan-pr.yml
Labels: ignore for release

#410 Update readme and readme typos
  README.md
  docs/frogbot-config.md
  docs/install-azure-pipelines.md
  docs/install-bitbucket-server.md
  docs/install-github.md
  docs/install-gitlab.md
  docs/templates/github-actions/README.md
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-dotnet.yml
Labels: ignore for release

#407 Display Contextual Analysis Column If Results Exist
  commands/createfixpullrequests.go
  commands/scanpullrequest.go
  commands/scanpullrequest_test.go
  commands/scanpullrequests_test.go
  commands/testdata/scanpullrequest/expectedResponse.json
  commands/testdata/scanpullrequest/expectedResponseMultiDir.json
  commands/utils/consts.go
  commands/utils/outputwriter.go
  commands/utils/simplifiedoutput.go
  commands/utils/simplifiedoutput_test.go
  commands/utils/standardoutput.go
  commands/utils/standardoutput_test.go
Labels: bug

#416 Rename resolver repository field to depsRepo to avoid confusion with Git repository
  commands/scanpullrequest.go
  commands/utils/depsutil.go
  commands/utils/depsutil_test.go
  commands/utils/packagehandlers/commonpackagehandler.go
  commands/utils/params.go
  commands/utils/params_test.go
Labels: ignore for release

#417 Remove redundant yaml.v2 dependency
  go.mod
  schema/schemas_test.go
Labels: ignore for release

#415 Fix wrong repository downloading and download branches only once
  commands/scanandfixrepos.go
  commands/scanpullrequest.go
  commands/utils/scandetails.go
  commands/utils/utils.go
Labels: bug

#418 Improve internal field names
  commands/commands.go
  commands/createfixpullrequests_test.go
  commands/scanandfixrepos_test.go
  commands/scanpullrequest_test.go
  commands/scanpullrequests_test.go
  commands/utils/git_test.go
  commands/utils/params.go
  commands/utils/params_test.go
  commands/utils/utils.go
Labels: ignore for release

#420 Fix aggregate PRs test
  commands/createfixpullrequests_test.go
  commands/scanpullrequest.go
  commands/utils/params_test.go
Labels: ignore for release

#427 Update Git Action dependencies
  action/lib/main.js
  action/lib/src/main.js
  action/lib/src/utils.js
  action/lib/test/main.spec.js
  action/lib/utils.js
  action/node_modules/.package-lock.json
  action/package-lock.json
  action/package.json
  action/src/main.ts
  action/src/utils.ts
  action/test/main.spec.ts
Labels: improvement

#429 Fix mock import
  .github/workflows/analysis.yml
  .github/workflows/cla.yml
  commands/scanpullrequest/scanallpullrequests_test.go
  commands/scanpullrequest/scanpullrequest_test.go
  commands/scanrepository/scanrepository_test.go
  commands/utils/testsutils.go
  go.mod
  go.sum
Labels: ignore for release

#428 Fix undefined pull request ID in scan-pull-requests
  action/node_modules/.package-lock.json
  commands/scanpullrequest/scanallpullrequests.go
  commands/scanpullrequest/scanpullrequest.go
  commands/scanpullrequest/scanpullrequest_test.go
  commands/utils/params.go
  commands/utils/params_test.go
Labels: bug

#431 Remove base branch from github actions
  .github/workflows/test.yml
  action/lib/utils.js
  action/src/utils.ts
Labels: bug

#432 Separate env params extraction by context
  commands/utils/params.go
  commands/utils/params_test.go
  go.sum
Labels: bug

#435 Update dependencies
  commands/scanpullrequest/scanpullrequest_test.go
  commands/testdata/indirect-projects/go/go.sum
  go.mod
  go.sum
Labels: ignore for release

#437 Fix scan-and-fix-repos faulty checkout
  .github/ISSUE_TEMPLATE/bug_report.yml
  commands/scanrepository/scanmultiplerepositories.go
  commands/scanrepository/scanrepository.go
  commands/utils/scandetails.go
Labels: bug

#441 Fix broken image links in the documentation
  README.md
Labels: ignore for release

#442 Make email receivers optional
  commands/utils/email.go
  commands/utils/email_test.go
  commands/utils/params.go
  docs/install-azure-pipelines.md
  docs/install-bitbucket-server.md
  docs/install-github.md
  docs/install-gitlab.md
  docs/templates/github-actions/frogbot-scan-pull-request.yml
  docs/templates/github-actions/frogbot-scan-repository.yml
  docs/templates/jenkins/scan-pull-request.jenkinsfile
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
  starter-workflows/README.md
  starter-workflows/code-scanning/frogbot-scan-and-fix.yml
  starter-workflows/code-scanning/frogbot-scan-pr.yml
  starter-workflows/code-scanning/properties/frogbot-scan-and-fix.properties.json
  starter-workflows/code-scanning/properties/frogbot-scan-pr.properties.json
  starter-workflows/icons/frogbot.svg
Labels: improvement

#447 Return github-actions folder
  docs/install-github.md
  docs/templates/github-actions/frogbot-scan-pull-request.yml
  docs/templates/github-actions/frogbot-scan-repository.yml
Labels: ignore for release

#424 Improve Azure Repos docs
  docs/install-azure-pipelines.md
  images/azure-build-policy.png
Labels: improvement

#449 Update install-azure-pipelines.md
  docs/install-azure-pipelines.md
Labels: ignore for release

#450 Fixing error message for Yarn version's incompatibility
  commands/utils/packagehandlers/yarnpackagehandler.go
Labels: ignore for release

#456 Remove 'main.go' from buildAndUpload.sh
  release/buildAndUpload.sh
Labels: ignore for release

#458 Update buildAndUpload.sh
  release/buildAndUpload.sh
Labels: ignore for release

#459 Add .git with remote details before clone if needed
  .frogbot/frogbot-config.yml
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  go.mod
  go.sum
  scanpullrequest/scanpullrequest_test.go
  scanrepository/scanmultiplerepositories_test.go
  scanrepository/scanrepository.go
  utils/git.go
  utils/git_test.go
Labels: bug

#426 New usage reporting
  commands.go
  go.mod
  go.sum
  utils/utils.go
  utils/utils_test.go
Labels: improvement

#463 Fix Scan-Pull-Request workflow
  .github/workflows/frogbot-scan-pr.yml
Labels: ignore for release

#462 Combining UpdateDependency test for all package managers
  packagehandlers/packagehandlers_test.go
Labels: ignore for release

#453 Create fix pull request - NuGet & .NET
  README.md
  go.mod
  go.sum
  packagehandlers/commonpackagehandler.go
  packagehandlers/nugetpackagehandler.go
  packagehandlers/packagehandlers_test.go
  packagehandlers/pythonpackagehandler.go
  scanrepository/scanrepository_test.go
  testdata/projects/nuget/Program.cs
  testdata/projects/nuget/nuget.csproj
  testdata/projects/nuget/obj/nuget.csproj.nuget.dgspec.json
  testdata/projects/nuget/obj/nuget.csproj.nuget.g.props
  testdata/projects/nuget/obj/nuget.csproj.nuget.g.targets
  testdata/projects/nuget/obj/project.assets.json
  testdata/projects/nuget/obj/project.nuget.cache
Labels: new feature

#460 Add CVE to comment dependency description title
  scanpullrequest/scanallpullrequests_test.go
  scanpullrequest/scanpullrequest_test.go
  scanrepository/scanrepository_test.go
  testdata/scanpullrequest/expectedResponse.json
  testdata/scanpullrequest/expectedResponseMultiDir.json
  utils/outputwriter/outputwriter.go
  utils/outputwriter/simplifiedoutput.go
  utils/outputwriter/simplifiedoutput_test.go
  utils/outputwriter/standardoutput.go
  utils/outputwriter/standardoutput_test.go
Labels: improvement

#465 Revert "Add CVE to comment dependency description title"
  scanpullrequest/scanallpullrequests_test.go
  scanpullrequest/scanpullrequest_test.go
  scanrepository/scanrepository_test.go
  testdata/scanpullrequest/expectedResponse.json
  testdata/scanpullrequest/expectedResponseMultiDir.json
  utils/outputwriter/outputwriter.go
  utils/outputwriter/simplifiedoutput.go
  utils/outputwriter/simplifiedoutput_test.go
  utils/outputwriter/standardoutput.go
  utils/outputwriter/standardoutput_test.go
Labels: ignore for release
