Repository jfrog/frogbot, pull requests merged in 2023-04, with the labels that each got.

#275 Update Frogbot's release, tests and templates to use Go 1.20.x
  .github/workflows/analysis.yml
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/test.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml
  release/pipelines.yml
Labels: improvement

#268 Avoid unnecessary rescans
  commands/scanandfixrepos.go
  commands/scanandfixrepos_test.go
  commands/utils/consts.go
  docs/templates/jfrog-pipelines/pipelines-go.yml
  go.mod
  go.sum
Labels: improvement

#279 Fix release pipeline
  release/pipelines.yml
Labels: ignore for release

#280 Release automation - merge to dev
  release/pipelines.yml
Labels: ignore for release

#274 Add notes to the documentation
  docs/frogbot-config.md
  docs/templates/github-actions/README.md
Labels: ignore for release

#281 Downgrade go to 1.19.x
  .github/workflows/analysis.yml
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/test.yml
  commands/scanandfixrepos.go
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  go.mod
  release/pipelines.yml
Labels: ignore for release

#282 Update Readme
  docs/frogbot-config.md
Labels: ignore for release

#286 Update docs
  docs/frogbot-config.md
Labels: ignore for release

#287 Update v2.6.2
  starter-workflows/code-scanning/frogbot-scan-and-fix.yml
  starter-workflows/code-scanning/frogbot-scan-pr.yml
Labels: ignore for release

#290 Optional install command for Npm projects
  go.mod
  go.sum
Labels: improvement

#283 Remove gradle extractor and use gradle-dep-tree
  commands/createfixpullrequests.go
  commands/scanandfixrepos_test.go
  commands/scanpullrequest.go
  commands/scanpullrequest_test.go
  commands/utils/extractors.go
  commands/utils/extractors_test.go
  commands/utils/params.go
  commands/utils/params_test.go
  commands/utils/utils.go
  go.mod
  go.sum
Labels: improvement

#292 Fix remote repository URL in documentation
  docs/install-azure-repos.md
  docs/install-bitbucket-server.md
  docs/install-github.md
  docs/install-gitlab.md
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-dotnet.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-gradle.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-maven.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-npm.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-nuget.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pip.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pipenv.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-poetry.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-yarn.yml
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
  starter-workflows/code-scanning/frogbot-scan-and-fix.yml
  starter-workflows/code-scanning/frogbot-scan-pr.yml
Labels: ignore for release

#293 Update PR scan table in the documentation
  README.md
Labels: ignore for release

#294 Avoid creating multiple merge requests
  commands/createfixpullrequests.go
  commands/createfixpullrequests_test.go
  commands/utils/packagehandlers/genericpackagehandler.go
  commands/utils/packagehandlers/gopackagehandler.go
  commands/utils/packagehandlers/mavenpackagehandler.go
  commands/utils/packagehandlers/packagehandlers_test.go
  commands/utils/packagehandlers/pythonpackagehandler.go
  commands/utils/utils.go
  commands/utils/utils_test.go
Labels: bug

#295 Fix commit to master bug
  commands/createfixpullrequests.go
Labels: bug

#298 Delete 'npm i' from the documentation and tests
  commands/testdata/config/frogbot-config-clean-test-proj.yml
  commands/testdata/config/frogbot-config-multi-dir-test-proj-no-fail.yml
  commands/testdata/config/frogbot-config-multi-dir-test-proj.yml
  commands/testdata/config/frogbot-config-scan-and-fix-repos.yml
  commands/testdata/config/frogbot-config-test-params.yml
  commands/testdata/config/frogbot-config-test-proj-no-fail.yml
  commands/testdata/config/frogbot-config-test-proj-subdir.yml
  commands/testdata/config/frogbot-config-test-proj.yml
  commands/testdata/config/frogbot-config-test-unmarshal.yml
  commands/utils/params_test.go
  docs/frogbot-config.md
  docs/install-azure-repos.md
  docs/install-bitbucket-server.md
  docs/install-github.md
  docs/install-gitlab.md
  docs/templates/.frogbot/frogbot-config.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-dotnet.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-npm.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-nuget.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-yarn.yml
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
  schema/frogbot-schema.json
  starter-workflows/code-scanning/frogbot-scan-and-fix.yml
  starter-workflows/code-scanning/frogbot-scan-pr.yml
Labels: ignore for release

#299 Add a static badge for Frogbot
  README.md
  images/frogbot-badge.svg
Labels: new feature

#307 Allow custom templates for messages, branches and PRs
  commands/createfixpullrequests.go
  commands/createfixpullrequests_test.go
  commands/testdata/config/frogbot-config-test-params.yml
  commands/utils/consts.go
  commands/utils/git.go
  commands/utils/git_test.go
  commands/utils/packagehandlers/genericpackagehandler.go
  commands/utils/packagehandlers/gopackagehandler.go
  commands/utils/packagehandlers/mavenpackagehandler.go
  commands/utils/packagehandlers/packagehandlers_test.go
  commands/utils/packagehandlers/pythonpackagehandler.go
  commands/utils/params.go
  commands/utils/params_test.go
  commands/utils/utils.go
  commands/utils/utils_test.go
  docs/templates/.frogbot/frogbot-config.yml
  go.mod
  go.sum
  images/frogbot-badge.png
  images/frogbot-badge.svg
  schema/frogbot-schema.json
Labels: new feature

#304 Add scheduled scanning to the templates for GitLab and GitHub
  .github/workflows/frogbot-scan-and-fix.yml
  action/lib/main.js
  action/node_modules/.package-lock.json
  action/src/main.ts
  docs/install-gitlab.md
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
  starter-workflows/code-scanning/frogbot-scan-and-fix.yml
Labels: improvement

#309 Support Git templates variables
  commands/utils/consts.go
  commands/utils/params.go
  commands/utils/params_test.go
  docs/frogbot-config.md
  docs/install-azure-repos.md
  docs/install-bitbucket-server.md
  docs/install-github.md
  docs/install-gitlab.md
  docs/templates/.frogbot/frogbot-config.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
  starter-workflows/code-scanning/frogbot-scan-and-fix.yml
Labels: new feature

#310 Allow major fix versions
  commands/createfixpullrequests.go
  commands/createfixpullrequests_test.go
  commands/utils/utils.go
  go.mod
  go.sum
Labels: improvement

#312 Fix poetry test
  .github/workflows/cla.yml
  commands/testdata/projects/poetry/poetry.lock
Labels: ignore for release

#316 Update Frogbot GitHub Action name and description
  action.yml
Labels: ignore for release

#315 Frogbot shouldn't attempt upgrading Go and Pip
  commands/createfixpullrequests.go
  commands/createfixpullrequests_test.go
  commands/utils/packagehandlers/genericpackagehandler.go
  commands/utils/packagehandlers/gopackagehandler.go
  commands/utils/packagehandlers/pythonpackagehandler.go
  commands/utils/utils.go
Labels: bug

#314 Allow optionally aggregating all fixes into one pull request
  commands/createfixpullrequests.go
  commands/testdata/config/frogbot-config-test-params.yml
  commands/utils/consts.go
  commands/utils/git.go
  commands/utils/git_test.go
  commands/utils/params.go
  commands/utils/params_test.go
  commands/utils/utils.go
  commands/utils/utils_test.go
  docs/install-azure-repos.md
  docs/install-bitbucket-server.md
  docs/install-github.md
  docs/install-gitlab.md
  docs/templates/.frogbot/frogbot-config.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-dotnet.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-gradle.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-maven.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-npm.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-nuget.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pip.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pipenv.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-poetry.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-yarn.yml
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
  schema/frogbot-schema.json
  starter-workflows/code-scanning/frogbot-scan-and-fix.yml
  starter-workflows/code-scanning/frogbot-scan-pr.yml
Labels: new feature

#321 fix tests
  commands/utils/git_test.go
  commands/utils/params_test.go
Labels: ignore for release
