Repository jfrog/frogbot, pull requests merged in 2023-11, with the labels that each got.

#555 Audit SCA recursive scan
  docs/frogbot-config.md
  docs/install-azure-pipelines.md
  docs/install-gitlab.md
  docs/templates/.frogbot/frogbot-config.yml
  docs/templates/github-actions/frogbot-scan-pull-request.yml
  docs/templates/github-actions/frogbot-scan-repository.yml
  docs/templates/jenkins/scan-pull-request.jenkinsfile
  docs/templates/jenkins/scan-repository.jenkinsfile
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
  go.mod
  go.sum
  scanpullrequest/scanpullrequest.go
  scanpullrequest/scanpullrequest_test.go
  scanrepository/scanrepository.go
  scanrepository/scanrepository_test.go
  schema/frogbot-schema.json
  utils/consts.go
  utils/params.go
  utils/scandetails.go
  utils/utils.go
Labels: new feature

#567 Avoid broken linked images at scan result
  commands.go
  go.mod
  go.sum
  scanpullrequest/scanallpullrequests.go
  scanpullrequest/scanallpullrequests_test.go
  scanpullrequest/scanpullrequest.go
  scanpullrequest/scanpullrequest_test.go
  scanrepository/scanmultiplerepositories.go
  scanrepository/scanmultiplerepositories_test.go
  scanrepository/scanrepository.go
  scanrepository/scanrepository_test.go
  utils/outputwriter/icons.go
  utils/outputwriter/outputcontent.go
  utils/outputwriter/outputcontent_test.go
  utils/outputwriter/outputwriter.go
  utils/outputwriter/standardoutput.go
  utils/outputwriter/standardoutput_test.go
  utils/testsutils.go
  utils/utils.go
  utils/utils_test.go
Labels: bug

#569 Promote dependencies for release
  go.mod
  go.sum
Labels: ignore for release

#568 Move the documentation to the new documentation site
  README.md
  docs/frogbot-config.md
  docs/install-azure-pipelines.md
  docs/install-github.md
  docs/install-gitlab.md
  docs/templates/.frogbot/frogbot-config.yml
  docs/templates/github-actions/frogbot-scan-pull-request.yml
  docs/templates/github-actions/frogbot-scan-repository.yml
  docs/templates/jenkins/README.md
  docs/templates/jenkins/scan-pull-request.jenkinsfile
  docs/templates/jenkins/scan-repository.jenkinsfile
  docs/templates/jfrog-pipelines/README.md
Labels: ignore for release

#571 Add .git to default exclusions patterns
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
  schema/frogbot-schema.json
Labels: ignore for release

#573 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#574 Fix Frogbot schema tests
  schema/schemas_test.go
Labels: ignore for release

#577 Fix CheckConnection race condition
  .github/workflows/test.yml
  utils/testsutils.go
  utils/utils.go
  utils/utils_test.go
Labels: bug

#575 Scan repository - show license violation on Github security issues
  go.mod
  go.sum
  scanpullrequest/scanpullrequest.go
  scanpullrequest/scanpullrequest_test.go
  scanrepository/scanrepository.go
  utils/utils.go
  utils/utils_test.go
Labels: improvement

#578 Fix frogbot-config.yml unread in the scan repository commands
  utils/params.go
Labels: bug

#579 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#576 Incorporate maven-dep-tree plugin
  go.mod
  go.sum
  packagehandlers/commonpackagehandler.go
  packagehandlers/mavenpackagehandler.go
  packagehandlers/packagehandlers_test.go
  packagehandlers/resources/maven-gav-reader.jar
Labels: improvement

#565 Applying auto-install modifications on a new 'fix' branch + restricting Frogbot's auto-install feature for Yarn
  go.mod
  go.sum
  scanrepository/scanrepository.go
  utils/git.go
  utils/git_test.go
  utils/scandetails.go
  utils/scanrepository.go
Labels: improvement

#588 Add informative errors for the unmarshaling processes in the MavenPackageHandler
  packagehandlers/mavenpackagehandler.go
Labels: improvement

#589 Fix false positive golangci-linter typecheck error
  scanrepository/scanrepository.go
Labels: bug

#581 Deprecate auto-install
  go.mod
  go.sum
  packagehandlers/packagehandlers_test.go
  scanrepository/scanrepository_test.go
  testdata/projects/nuget/Program.cs
  testdata/projects/nuget/core/Multi1.cs
  testdata/projects/nuget/core/Properties/AssemblyInfo.cs
  testdata/projects/nuget/core/core.csproj
  testdata/projects/nuget/core/core.nuspec
  testdata/projects/nuget/core/packages.config
  testdata/projects/nuget/example.sln
  testdata/projects/nuget/nuget.csproj
  testdata/projects/nuget/obj/nuget.csproj.nuget.dgspec.json
  testdata/projects/nuget/obj/nuget.csproj.nuget.g.props
  testdata/projects/nuget/obj/nuget.csproj.nuget.g.targets
  testdata/projects/nuget/obj/project.assets.json
  testdata/projects/nuget/obj/project.nuget.cache
  utils/depsutil.go
  utils/depsutil_test.go
  utils/scandetails.go
  utils/scandetails_test.go
Labels: improvement

#583 Added Azure integration tests
  .github/workflows/test.yml
  azure_test.go
  github_test.go
  go.mod
  go.sum
  integrationutils.go
  utils/git.go
Labels: ignore for release
