Repository jfrog/frogbot, pull requests merged in 2023-05, with the labels that each got.

#320 Avoid pushing empty branches to remote
  commands/createfixpullrequests.go
  commands/scanandfixrepos.go
  commands/utils/git.go
Labels: bug

#322 Filter by min severity & no fix version vulnerabilities
  commands/createfixpullrequests.go
  commands/createfixpullrequests_test.go
  commands/scanandfixrepos.go
  commands/scanpullrequest.go
  commands/scanpullrequest_test.go
  commands/testdata/config/frogbot-config-test-params.yml
  commands/utils/consts.go
  commands/utils/depsutil_test.go
  commands/utils/params.go
  commands/utils/params_test.go
  commands/utils/scandetails.go
  commands/utils/scandetails_test.go
  commands/utils/utils.go
  docs/install-azure-repos.md
  docs/install-bitbucket-server.md
  docs/install-github.md
  docs/install-gitlab.md
  docs/templates/.frogbot/frogbot-config.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-dotnet.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-gradle.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-maven.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-npm.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-nuget.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pip.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pipenv.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-poetry.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-yarn.yml
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
  go.mod
  go.sum
  schema/frogbot-schema.json
Labels: new feature

#326 Add Golangci-lint static code analysis and fix found issues
  .github/workflows/analysis.yml
  commands/createfixpullrequests_test.go
  commands/scanandfixrepos_test.go
  commands/scanpullrequest_test.go
  commands/scanpullrequests_test.go
  schema/schemas_test.go
Labels: improvement

#328 Frogbot may fail for Azure Repos due to a bug in the "fetch commit status" API
  commands/scanandfixrepos.go
  commands/utils/utils.go
  go.mod
  go.sum
Labels: bug

#329 Documentation improvements
  README.md
  images/frogbot-screencast.png
Labels: ignore for release

#332 Upgrade froggit-go to v1.7.3, which includes bug fixes
  go.mod
  go.sum
Labels: bug

#335 Extend the go-git timeout to 60 seconds
  commands/utils/git.go
Labels: bug

#340 Update workflows templates
  .github/workflows/action-test.yml
  .github/workflows/analysis.yml
  .github/workflows/frogbot-scan-and-fix.yml
  docs/install-azure-repos.md
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
  starter-workflows/code-scanning/frogbot-scan-and-fix.yml
Labels: ignore for release

#342 Fix scan-pull-request target scan
  commands/createfixpullrequests.go
  commands/scanpullrequest.go
  commands/utils/depsutil.go
  commands/utils/utils.go
  go.mod
  go.sum
Labels: bug

#336 Refactor Maven logic and integrate maven-gav-reader plugin
  commands/createfixpullrequests.go
  commands/createfixpullrequests_test.go
  commands/testdata/packagehandlers/pom.xml
  commands/utils/mavenutils.go
  commands/utils/mavenutils_test.go
  commands/utils/packagehandlers/genericpackagehandler.go
  commands/utils/packagehandlers/mavenpackagehandler.go
  commands/utils/packagehandlers/packagehandlers_test.go
  commands/utils/packagehandlers/resources/maven-gav-reader.jar
  commands/utils/utils.go
Labels: improvement

#338 Update dependencies & Update Go to 1.20.x
  .github/workflows/analysis.yml
  .github/workflows/frogbot-scan-and-fix.yml
  .github/workflows/frogbot-scan-pr.yml
  .github/workflows/test.yml
  commands/scanpullrequest_test.go
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml
  go.mod
  go.sum
  release/pipelines.yml
Labels: dependencies

#343 Fix GitHub actions templates
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
  starter-workflows/code-scanning/frogbot-scan-and-fix.yml
Labels: ignore for release

#317 Fix indirect dependancies in Golang & Improve logging
  commands/createfixpullrequests.go
  commands/createfixpullrequests_test.go
  commands/scanandfixrepos.go
  commands/testdata/indirect-projects/go/go.mod
  commands/testdata/indirect-projects/go/main.go
  commands/testdata/indirect-projects/maven/pom.xml
  commands/testdata/indirect-projects/pip/requirements.txt
  commands/testdata/indirect-projects/pip/setup.py
  commands/testdata/indirect-projects/pipenv/Pipfile
  commands/testdata/indirect-projects/pipenv/Pipfile.lock
  commands/testdata/indirect-projects/poetry/pyproject.toml
  commands/utils/consts.go
  commands/utils/git.go
  commands/utils/git_test.go
  commands/utils/packagehandlers/commonPackageHandler.go
  commands/utils/packagehandlers/genericpackagehandler.go
  commands/utils/packagehandlers/gopackagehandler.go
  commands/utils/packagehandlers/mavenpackagehandler.go
  commands/utils/packagehandlers/npmpackagehandler.go
  commands/utils/packagehandlers/packagehandlers_test.go
  commands/utils/packagehandlers/pythonpackagehandler.go
  commands/utils/packagehandlers/yarnpackagehandler.go
  commands/utils/params.go
  commands/utils/utils.go
  commands/utils/utils_test.go
Labels: improvement

#344 Update ReadMe & Github Workflow
  .github/workflows/frogbot-scan-and-fix.yml
  README.md
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-dotnet.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-gradle.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-maven.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-npm.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-nuget.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pip.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pipenv.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-poetry.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-yarn.yml
  starter-workflows/code-scanning/frogbot-scan-pr.yml
Labels: ignore for release

#348 Fix typo in docs
  README.md
Labels: ignore for release

#351 Infinite loop while parsing Npm dependency list
  go.mod
  go.sum
Labels: bug
