Repository jfrog/frogbot, pull requests merged in 2023-07, with the labels that each got.

#376 Fix identification of existing pull request on Bitbucket Server
  commands/createfixpullrequests.go
  go.mod
  go.sum
Labels: bug

#377 Customize commit email author
  .github/workflows/frogbot-scan-and-fix.yml
  commands/testdata/config/frogbot-config-test-unmarshal.yml
  commands/utils/consts.go
  commands/utils/git.go
  commands/utils/params.go
  commands/utils/params_test.go
  docs/install-azure-repos.md
  docs/install-bitbucket-server.md
  docs/install-github.md
  docs/install-gitlab.md
  docs/templates/.frogbot/frogbot-config.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
  go.mod
  go.sum
  schema/frogbot-schema.json
Labels: new feature

#378 Fix extract Frogbot configuration from source branch
  commands/utils/params.go
Labels: bug

#388 Update install-gitlab.md template
  docs/install-gitlab.md
Labels: ignore for release

#389 Fix templates
  .github/workflows/frogbot-scan-and-fix.yml
  docs/install-azure-repos.md
  docs/install-bitbucket-server.md
  docs/install-github.md
  docs/install-gitlab.md
  docs/templates/.frogbot/frogbot-config.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
  starter-workflows/code-scanning/frogbot-scan-and-fix.yml
Labels: ignore for release

#394 Improve git error logs on test
  commands/createfixpullrequests_test.go
Labels: ignore for release

#393 Update dependencies
  .github/workflows/test.yml
  commands/createfixpullrequests.go
  commands/createfixpullrequests_test.go
  commands/testdata/createfixpullrequests/aggregate-no-vul/git/COMMIT_EDITMSG
  commands/testdata/createfixpullrequests/aggregate-no-vul/git/index
  commands/testdata/createfixpullrequests/aggregate-no-vul/git/logs/HEAD
  commands/testdata/createfixpullrequests/aggregate-no-vul/git/logs/refs/heads/main
  commands/testdata/createfixpullrequests/aggregate-no-vul/git/objects/49/a00e6f645bdc847b9d91154e45f851d40232b4
  commands/testdata/createfixpullrequests/aggregate-no-vul/git/objects/68/9eb74b5751deacb06bb123bcb49b55e66c12f3
  commands/testdata/createfixpullrequests/aggregate-no-vul/git/objects/6e/a5e6ad52f49a83069bc8b09413433004ce9738
  commands/testdata/createfixpullrequests/aggregate-no-vul/git/objects/8f/0367ad4ed1c130c1bec08705a8c997918bc7a8
  commands/testdata/createfixpullrequests/aggregate-no-vul/git/objects/a0/d3b6d6c181f883b31a153f98b71b4570c1917e
  commands/testdata/createfixpullrequests/aggregate-no-vul/git/objects/a6/600a47f296f285b38cb470431919dca3d16274
  commands/testdata/createfixpullrequests/aggregate-no-vul/git/objects/b0/76db7d395d21ccc44b5a9eb858475052da850f
  commands/testdata/createfixpullrequests/aggregate-no-vul/git/refs/heads/main
  commands/testdata/createfixpullrequests/aggregate-no-vul/package-lock.json
  commands/testdata/createfixpullrequests/aggregate-no-vul/package.json
  commands/testdata/createfixpullrequests/aggregate/git/COMMIT_EDITMSG
  commands/testdata/createfixpullrequests/aggregate/git/index
  commands/testdata/createfixpullrequests/aggregate/git/logs/HEAD
  commands/testdata/createfixpullrequests/aggregate/git/logs/refs/heads/main
  commands/testdata/createfixpullrequests/aggregate/git/objects/0b/0bc897474ade0656ffb59bde78495cbb0215ed
  commands/testdata/createfixpullrequests/aggregate/git/objects/1a/4f13d84cd5037f0ced095ff6768303e00e1ccb
  commands/testdata/createfixpullrequests/aggregate/git/objects/48/9bbb4e8d38d8fdc0ad145e95c0cbcb056207da
  commands/testdata/createfixpullrequests/aggregate/git/objects/49/a00e6f645bdc847b9d91154e45f851d40232b4
  commands/testdata/createfixpullrequests/aggregate/git/objects/4f/8cb57f89f9abfb6f00fa751db57e2b9b9191e3
  commands/testdata/createfixpullrequests/aggregate/git/objects/6c/ca312ff774d83d1fe05c4a2754b09afe8a96af
  commands/testdata/createfixpullrequests/aggregate/git/objects/6e/a5e6ad52f49a83069bc8b09413433004ce9738
  commands/testdata/createfixpullrequests/aggregate/git/objects/8f/0367ad4ed1c130c1bec08705a8c997918bc7a8
  commands/testdata/createfixpullrequests/aggregate/git/objects/9f/096a4259c970222bc8287ab53038851b2b9879
  commands/testdata/createfixpullrequests/aggregate/git/objects/c5/ea932251daf109838c67f30cd5091f28c801fc
  commands/testdata/createfixpullrequests/aggregate/git/objects/de/464c09022d09bf206639aa97702dd735c997ff
  commands/testdata/createfixpullrequests/aggregate/git/refs/heads/main
  commands/testdata/createfixpullrequests/aggregate/package-lock.json
  commands/testdata/createfixpullrequests/aggregate/package.json
  commands/testdata/createfixpullrequests/non-aggregate/git/COMMIT_EDITMSG
  commands/testdata/createfixpullrequests/non-aggregate/git/index
  commands/testdata/createfixpullrequests/non-aggregate/git/logs/HEAD
  commands/testdata/createfixpullrequests/non-aggregate/git/logs/refs/heads/main
  commands/testdata/createfixpullrequests/non-aggregate/git/objects/0b/b00a51656f0f37fffa341307939f0ce2a6f710
  commands/testdata/createfixpullrequests/non-aggregate/git/objects/1e/65421dbebea0a4f4a2ff6223d1943868de364b
  commands/testdata/createfixpullrequests/non-aggregate/git/objects/5c/4b711177241bf89036cb06a604913bb9c76519
  commands/testdata/createfixpullrequests/non-aggregate/git/objects/6b/1cecf8c1903b6d8cf414457818cb9b92f9b8a0
  commands/testdata/createfixpullrequests/non-aggregate/git/objects/92/72e52780ce707ecf8bad817b435e3fe3342fbd
  commands/testdata/createfixpullrequests/non-aggregate/git/objects/be/2ac309d07d949b362883168a920f27eb046076
  commands/testdata/createfixpullrequests/non-aggregate/git/objects/d6/63c36588e0906b96de4a2eb190b8cecb252c3a
  commands/testdata/createfixpullrequests/non-aggregate/git/objects/e0/16d1bccf9581d380b5245ac0042769f66bfa4a
  commands/testdata/createfixpullrequests/non-aggregate/git/objects/e1/7dbb822897a530543c58d304b7b93b77a34bb0
  commands/testdata/createfixpullrequests/non-aggregate/git/objects/ee/89d7cc731a49bd7f00bdc4a333190f3aca7eec
  commands/testdata/createfixpullrequests/non-aggregate/git/refs/heads/main
  commands/testdata/createfixpullrequests/non-aggregate/package-lock.json
  commands/testdata/createfixpullrequests/non-aggregate/package.json
  commands/testdata/scanpullrequest/expectedResponseMultiDir.json
  go.mod
  go.sum
Labels: ignore for release

#392 Add informative error for unsupported technologies in create-fix-pull-requests
  commands/createfixpullrequests.go
  commands/utils/packagehandlers/commonpackagehandler.go
  commands/utils/packagehandlers/unsupportedpackagehandler.go
Labels: bug

#396 Fix release intergation
  release/pipelines.yml
Labels: ignore for release

#371 Documentation updates - with IaC and Secrets
  README.md
Labels: ignore for release

#400 Remove old comments in pull requests
  commands/createfixpullrequests.go
  commands/createfixpullrequests_test.go
  commands/scanpullrequest.go
  commands/scanpullrequest_test.go
  commands/scanpullrequests.go
  commands/scanpullrequests_test.go
  commands/testdata/messages/novulnerabilities.md
  commands/testdata/messages/novulnerabilitiesMR.md
  commands/testdata/scanpullrequest/commits.json
  commands/testdata/scanpullrequest/expectedResponse.json
  commands/testdata/scanpullrequest/expectedResponseMultiDir.json
  commands/utils/icons.go
  commands/utils/icons_test.go
  commands/utils/packagehandlers/packagehandlers_test.go
  commands/utils/simplifiedoutput.go
  commands/utils/standardoutput.go
  commands/utils/standardoutput_test.go
  commands/utils/utils.go
  commands/utils/utils_test.go
  go.mod
  go.sum
Labels: improvement

#404 Scan Pull Request - change to relevant working dir before audit
  commands/scanpullrequest.go
  commands/utils/simplifiedoutput.go
  commands/utils/simplifiedoutput_test.go
  commands/utils/standardoutput.go
  commands/utils/standardoutput_test.go
  go.mod
  go.sum
Labels: bug

#406 Avoid deleting comments if none are found
  action/node_modules/.package-lock.json
  action/node_modules/semver/CHANGELOG.md
  action/node_modules/semver/package.json
  action/node_modules/semver/semver.js
  action/package-lock.json
  commands/scanpullrequest.go
  commands/scanpullrequest_test.go
Labels: bug
