Repository jfrog/frogbot, pull requests merged in 2023-06, with the labels that each got.

#354 Fix aggregated pull requests
  commands/createfixpullrequests.go
Labels: bug

#353 Remove setting commit build status
  commands/scanandfixrepos.go
  commands/scanandfixrepos_test.go
  commands/utils/utils.go
Labels: improvement

#358 Convert SSH clone urls to HTTPS
  commands/utils/git.go
  commands/utils/git_test.go
  commands/utils/params.go
  commands/utils/params_test.go
  docs/install-bitbucket-server.md
Labels: improvement

#330 Add getFrogbot.sh remote details in docs
  docs/install-azure-repos.md
  docs/install-bitbucket-server.md
  docs/install-github.md
  docs/install-gitlab.md
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
Labels: ignore for release

#359 Add JF_RELEASES_REPO to GitHub actions
  action/lib/utils.js
  action/package-lock.json
  action/package.json
  action/src/utils.ts
  action/test/main.spec.ts
Labels: bug

#363 Specify coordinates of the Maven versions plugin
  commands/utils/packagehandlers/mavenpackagehandler.go
Labels: bug

#352 Enable using environment variables along with frogbot-config.yml
  commands/commands.go
  commands/createfixpullrequests.go
  commands/createfixpullrequests_test.go
  commands/scanandfixrepos.go
  commands/scanandfixrepos_test.go
  commands/scanpullrequest.go
  commands/scanpullrequest_test.go
  commands/scanpullrequests.go
  commands/scanpullrequests_test.go
  commands/testdata/config/frogbot-config-test-params-merge.yml
  commands/utils/extractors.go
  commands/utils/extractors_test.go
  commands/utils/git.go
  commands/utils/git_test.go
  commands/utils/packagehandlers/pythonpackagehandler.go
  commands/utils/params.go
  commands/utils/params_test.go
  commands/utils/utils.go
  go.mod
Labels: improvement

#366 Fix version is not available in Maven
  commands/utils/packagehandlers/mavenpackagehandler.go
Labels: bug

#368 Utilize default project when undefined in frogbot-config.yml
  commands/testdata/config/frogbot-config-empty-scan.yml
  commands/utils/params.go
  commands/utils/params_test.go
Labels: bug

#357 Add Contextual Analysis + Improved UX
  README.md
  commands/createfixpullrequests.go
  commands/createfixpullrequests_test.go
  commands/scanpullrequest.go
  commands/scanpullrequest_test.go
  commands/scanpullrequests_test.go
  commands/testdata/messages/novulnerabilities.md
  commands/testdata/scanpullrequest/expectedResponse.json
  commands/testdata/scanpullrequest/expectedResponseMultiDir.json
  commands/utils/consts.go
  commands/utils/git.go
  commands/utils/git_test.go
  commands/utils/icons.go
  commands/utils/icons_test.go
  commands/utils/outputwriter.go
  commands/utils/outputwriter_test.go
  commands/utils/packagehandlers/commonpackagehandler.go
  commands/utils/packagehandlers/gopackagehandler.go
  commands/utils/packagehandlers/mavenpackagehandler.go
  commands/utils/packagehandlers/npmpackagehandler.go
  commands/utils/packagehandlers/packagehandlers_test.go
  commands/utils/packagehandlers/pythonpackagehandler.go
  commands/utils/packagehandlers/yarnpackagehandler.go
  commands/utils/simplifiedoutput.go
  commands/utils/simplifiedoutput_test.go
  commands/utils/standardoutput.go
  commands/utils/standardoutput_test.go
  commands/utils/utils.go
  commands/utils/utils_test.go
  go.mod
  go.sum
  resources/applicableCriticalSeverity.png
  resources/applicableHighSeverity.png
  resources/applicableLowSeverity.png
  resources/applicableMediumSeverity.png
  resources/applicableUnknownSeverity.png
  resources/criticalSeverity.png
  resources/highSeverity.png
  resources/lowSeverity.png
  resources/mediumSeverity.png
  resources/notApplicableCritical.png
  resources/notApplicableHigh.png
  resources/notApplicableLow.png
  resources/notApplicableMedium.png
  resources/notApplicableUnknown.png
Labels: new feature

#367 Restrict aggregate mode to a single active branch
  commands/createfixpullrequests.go
  commands/utils/consts.go
  commands/utils/git.go
  commands/utils/git_test.go
  commands/utils/params.go
  commands/utils/params_test.go
  commands/utils/utils.go
  commands/utils/utils_test.go
  go.mod
  go.sum
Labels: improvement

#370 Fix create fixing pull request for violations
  commands/createfixpullrequests.go
  commands/createfixpullrequests_test.go
  commands/utils/git.go
Labels: bug

#375 Fix the Frogbot badge link in the README
  README.md
Labels: ignore for release
