Repository jfrog/frogbot, pull requests merged in 2023-01, with the labels that each got.

#220 Fix duplicate code scanning alerts
  commands/utils/utils.go
  commands/utils/utils_test.go
  go.mod
  go.sum
Labels: bug

#221 Fix upload code scanning component deletion
  commands/createfixpullrequests.go
  commands/utils/utils.go
  commands/utils/utils_test.go
  go.mod
  go.sum
Labels: bug

#224 Add root dir to working dirs if project undefined
  commands/createfixpullrequests.go
  commands/scanpullrequest.go
  commands/scanpullrequests_test.go
  commands/utils/params.go
  commands/utils/params_test.go
  commands/utils/utils.go
Labels: bug

#225 Add JF_GIT_USERNAME to bitbucket server
  commands/createfixpullrequests.go
  commands/scanandfixrepos.go
  commands/utils/consts.go
  commands/utils/params.go
  docs/install-bitbucket-server.md
  go.mod
  go.sum
Labels: bug

#227 Update froggit go dependencies
  commands/utils/params.go
  go.mod
  go.sum
Labels: dependencies

#231 Update Dependencies
  go.mod
  go.sum
Labels: dependencies

#232 Verify Environment on GitHub Actions
  commands/scanpullrequest.go
  commands/scanpullrequest_test.go
  commands/utils/consts.go
Labels: improvement

#233 Create Frogbot config schema
  go.mod
  go.sum
  schema/frogbot-schema.json
  schema/frogbotschema_test.go
  schema/testdata/additional-prop.yml
  schema/testdata/empty-repo.yml
  schema/testdata/no-array.yml
  schema/testdata/no-git.yml
  schema/testdata/no-repo.yml
Labels: improvement

#230 Fix integration with JFrog Pipelines + Update documentation
  commands/commands.go
  commands/createfixpullrequests.go
  commands/scanandfixrepos_test.go
  commands/scanpullrequest.go
  commands/scanpullrequest_test.go
  commands/utils/git.go
  commands/utils/params.go
  commands/utils/params_test.go
  commands/utils/utils.go
  docs/frogbot-config.md
  docs/install-bitbucket-server.md
  docs/install-github.md
  docs/install-gitlab.md
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
Labels: bug

#228 Improve pull request comment and code scanning view
  commands/createfixpullrequests.go
  commands/createfixpullrequests_test.go
  commands/scanpullrequest.go
  commands/scanpullrequest_test.go
  commands/scanpullrequests_test.go
  commands/testdata/messages/dummyvulnerabilities.md
  commands/testdata/scanpullrequest/expectedResponse.json
  commands/testdata/scanpullrequest/expectedResponseMultiDir.json
  commands/testdata/scanpullrequest/expectedResponsePip.json
  commands/utils/consts.go
  commands/utils/utils.go
  commands/utils/utils_test.go
  go.mod
  go.sum
Labels: improvement

#235 Fix rescan issue
  commands/scanandfixrepos.go
  commands/utils/params.go
  commands/utils/utils.go
Labels: bug

#236 Add notice for open-source projects
  README.md
  docs/install-azure-repos.md
  docs/install-bitbucket-server.md
  docs/install-github.md
Labels: ignore for release

#234 Update starter-workflows
  docs/install-azure-repos.md
  docs/install-bitbucket-server.md
  docs/install-github.md
  docs/install-gitlab.md
  docs/templates/github-actions/README.md
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-dotnet.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-gradle.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-maven.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-npm.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-nuget.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pip.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pipenv.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-poetry.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-yarn.yml
  starter-workflows/code-scanning/frogbot-scan-and-fix.yml
  starter-workflows/code-scanning/frogbot-scan-pr.yml
Labels: improvement
