Repository jfrog/frogbot, pull requests merged in 2023-09, with the labels that each got.

#472 Update CLI-Core
  go.mod
  go.sum
Labels: ignore for release

#473 Update core
  .github/workflows/frogbot-scan-repository.yml
  go.mod
  go.sum
  utils/scandetails.go
Labels: ignore for release

#474 Update dependencies
  .github/workflows/test.yml
  go.mod
  go.sum
Labels: ignore for release

#476 Improve testing suite
  .github/workflows/test.yml
Labels: ignore for release

#480 Improve the `Potential secrets detected` email template
  utils/email.go
  utils/email_test.go
  utils/outputwriter/outputwriter.go
Labels: improvement

#481 Improve upload to security tab logs
  scanrepository/scanrepository.go
  utils/utils.go
Labels: improvement

#484 Merge core data changes
  go.mod
  go.sum
  scanpullrequest/scanpullrequest.go
  scanpullrequest/scanpullrequest_test.go
  utils/email.go
  utils/email_test.go
  utils/outputwriter/outputwriter.go
  utils/outputwriter/simplifiedoutput_test.go
  utils/outputwriter/standardoutput_test.go
  utils/utils.go
Labels: ignore for release

#451 Add Xray Source Control Service
  scanpullrequest/scanallpullrequests_test.go
  scanrepository/scanrepository.go
  scanrepository/scanrepository_test.go
  utils/params.go
  utils/scandetails.go
Labels: improvement

#486 Dont show remediation if not exists
  utils/outputwriter/outputwriter.go
  utils/outputwriter/simplifiedoutput.go
  utils/outputwriter/standardoutput.go
Labels: ignore for release

#485 Fix TestScanPullRequest
  go.mod
  go.sum
  scanpullrequest/scanallpullrequests_test.go
  scanpullrequest/scanpullrequest.go
  scanpullrequest/scanpullrequest_test.go
  scanrepository/scanrepository_test.go
  testdata/messages/novulnerabilities.md
  testdata/messages/novulnerabilitiesMR.md
  testdata/scanpullrequest/expectedResponse.json
  testdata/scanpullrequest/expectedResponseMultiDir.json
  testdata/scanpullrequest/list_merge_request_discussion_items.json
Labels: ignore for release

#487 Fix try to delete main comment at review
  utils/reviewcomment.go
Labels: bug

#488 Don't show remediation if not exists
  go.mod
  go.sum
  utils/outputwriter/outputwriter.go
  utils/outputwriter/simplifiedoutput.go
  utils/outputwriter/standardoutput.go
Labels: bug

#491 Add CVE info to contextual Analysis comment
  utils/outputwriter/outputwriter.go
  utils/outputwriter/simplifiedoutput.go
  utils/outputwriter/standardoutput.go
  utils/reviewcomment.go
Labels: improvement

#490 Pull Request - add cves to table
  scanpullrequest/scanallpullrequests_test.go
  scanpullrequest/scanpullrequest_test.go
  scanrepository/scanrepository_test.go
  testdata/messages/novulnerabilities.md
  testdata/messages/novulnerabilitiesMR.md
  testdata/scanpullrequest/expectedResponse.json
  testdata/scanpullrequest/expectedResponseMultiDir.json
  utils/outputwriter/outputwriter.go
  utils/outputwriter/simplifiedoutput.go
  utils/outputwriter/simplifiedoutput_test.go
  utils/outputwriter/standardoutput.go
  utils/outputwriter/standardoutput_test.go
Labels: improvement

#494 Fix GitHub delete review comments
  go.mod
  go.sum
  utils/reviewcomment.go
Labels: bug

#495 Show Xray ID instead of CVEs if empty in vulnerabilities description
  go.mod
  go.sum
  scanpullrequest/scanpullrequest_test.go
  utils/outputwriter/outputwriter.go
  utils/outputwriter/simplifiedoutput.go
  utils/outputwriter/standardoutput.go
Labels: improvement

#493 Add Shellcheck action and fix issues
  .github/workflows/analysis.yml
  .github/workflows/test.yml
  action/.husky/pre-commit
  buildscripts/build.sh
  buildscripts/getFrogbot.sh
  release/buildAndUpload.sh
Labels: ignore for release

#503 Add validate-pr-target-branch.yml action
  .github/workflows/validate-pr-target-branch.yml
Labels: ignore for release

#502 Download maven-install-plugin with JF_DEPS_REPO
  packagehandlers/mavenpackagehandler.go
Labels: bug

#498 Pull request scanning - add license report
  docs/install-azure-pipelines.md
  docs/install-gitlab.md
  docs/licenses.md
  docs/templates/.frogbot/frogbot-config.yml
  docs/templates/github-actions/frogbot-scan-pull-request.yml
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
  go.mod
  go.sum
  packagehandlers/commonpackagehandler.go
  packagehandlers/packagehandlers_test.go
  packagehandlers/pythonpackagehandler.go
  scanpullrequest/scanallpullrequests_test.go
  scanpullrequest/scanpullrequest.go
  scanpullrequest/scanpullrequest_test.go
  scanrepository/scanrepository.go
  scanrepository/scanrepository_test.go
  schema/frogbot-schema.json
  testdata/config/frogbot-config-test-params-merge.yml
  testdata/messages/novulnerabilities.md
  testdata/messages/novulnerabilitiesMR.md
  testdata/scanpullrequest/expectedResponse.json
  testdata/scanpullrequest/expectedResponseMultiDir.json
  utils/consts.go
  utils/depsutil.go
  utils/email.go
  utils/email_test.go
  utils/git.go
  utils/issuescollection.go
  utils/outputwriter/outputwriter.go
  utils/outputwriter/outputwriter_test.go
  utils/outputwriter/simplifiedoutput.go
  utils/outputwriter/simplifiedoutput_test.go
  utils/outputwriter/standardoutput.go
  utils/outputwriter/standardoutput_test.go
  utils/params.go
  utils/params_test.go
  utils/reviewcomment.go
  utils/scandetails.go
  utils/scandetails_test.go
  utils/testsutils.go
  utils/utils.go
  utils/utils_test.go
Labels: new feature

#504 Update Dependencies
  go.mod
  go.sum
Labels: ignore for release

#496 Fix Custom PR Title in Aggregated Mode
  scanrepository/scanrepository.go
  scanrepository/scanrepository_test.go
  utils/consts.go
  utils/git.go
  utils/git_test.go
  utils/outputwriter/outputwriter.go
  utils/outputwriter/outputwriter_test.go
  utils/utils.go
  utils/utils_test.go
Labels: bug

#507 Enforce mandatory JF_GIT_REPO param
  utils/params.go
  utils/params_test.go
Labels: bug

#506 Fix GoSec issues
  action/lib/utils.js
  action/node_modules/.package-lock.json
  action/package-lock.json
  action/src/utils.ts
  go.mod
  go.sum
  packagehandlers/mavenpackagehandler.go
  utils/depsutil.go
  utils/params.go
  utils/scandetails.go
Labels: ignore for release

#509 AggregateFixAndOpenPullRequest error handling panic fix
  scanrepository/scanrepository.go
Labels: bug, ignore for release

#510 Fix Multi Repository Scanning
  scanpullrequest/scanpullrequest_test.go
  scanrepository/scanmultiplerepositories_test.go
  scanrepository/scanrepository_test.go
  utils/params.go
  utils/params_test.go
Labels: bug

#512 Add error on usage when no repositories provided
  utils/utils.go
  utils/utils_test.go
Labels: bug

#513 Improve bad API endpoint error hint
  utils/params.go
Labels: ignore for release

#518 Remove research details section if empty
  scanpullrequest/scanpullrequest_test.go
  utils/outputwriter/simplifiedoutput.go
  utils/outputwriter/simplifiedoutput_test.go
  utils/outputwriter/standardoutput.go
  utils/outputwriter/standardoutput_test.go
Labels: bug
