Repository jfrog/frogbot, pull requests merged in 2023-03, with the labels that each got.

#242 Regex patterns are not efficient enough
  commands/utils/mavenutils.go
  commands/utils/mavenutils_test.go
Labels: bug

#245 Support Air Gapped environments
  buildscripts/getFrogbot.sh
  commands/commands.go
  commands/createfixpullrequests.go
  commands/createfixpullrequests_test.go
  commands/scanandfixrepos_test.go
  commands/scanpullrequest.go
  commands/scanpullrequest_test.go
  commands/scanpullrequests_test.go
  commands/testdata/projects/dotnet/Program.cs
  commands/testdata/projects/dotnet/dotnet.csproj
  commands/testdata/projects/gradle/build.gradle
  commands/testdata/projects/gradle/gradle/wrapper/gradle-wrapper.jar
  commands/testdata/projects/gradle/gradle/wrapper/gradle-wrapper.properties
  commands/testdata/projects/gradle/gradlew
  commands/testdata/projects/gradle/gradlew.bat
  commands/testdata/projects/gradle/src/main/template/Main.java
  commands/testdata/projects/npm/node_modules/.package-lock.json
  commands/testdata/projects/npm/package-lock.json
  commands/testdata/projects/npm/package.json
  commands/testdata/projects/yarn/.yarn/install-state.gz
  commands/testdata/projects/yarn/.yarn/releases/yarn-3.2.2.cjs
  commands/testdata/projects/yarn/.yarn/releases/yarn-3.4.1.cjs
  commands/testdata/projects/yarn/.yarnrc.yml
  commands/testdata/projects/yarn/package-lock.json
  commands/testdata/projects/yarn/package.json
  commands/testdata/projects/yarn/yarn-error.log
  commands/testdata/projects/yarn/yarn.lock
  commands/testdata/scanpullrequest/expectedResponse.json
  commands/utils/consts.go
  commands/utils/depsutil.go
  commands/utils/depsutil_test.go
  commands/utils/extractors.go
  commands/utils/extractors_test.go
  commands/utils/params.go
  commands/utils/params_test.go
  commands/utils/utils.go
  commands/utils/utils_test.go
  docs/frogbot-config.md
  docs/templates/.frogbot/frogbot-config.yml
  go.mod
  go.sum
  main.go
  main_test.go
  release/pipelines.yml
Labels: new feature

#258 Documentation changes
  README.md
  docs/frogbot-config.md
  docs/install-azure-repos.md
  docs/install-bitbucket-server.md
  docs/install-github.md
  docs/install-gitlab.md
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-dotnet.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-gradle.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-maven.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-npm.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-nuget.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pip.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pipenv.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-poetry.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-yarn.yml
  starter-workflows/code-scanning/frogbot-scan-and-fix.yml
  starter-workflows/code-scanning/frogbot-scan-pr.yml
Labels: ignore for release

#260 Update frogbot version
  commands/utils/consts.go
  commands/utils/utils.go
  release/buildAndUpload.sh
Labels: ignore for release

#259 Docs changes
  docs/install-azure-repos.md
  docs/install-bitbucket-server.md
  docs/install-github.md
  docs/install-gitlab.md
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-go.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-maven.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-npm.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pip.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-pipenv.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-poetry.yml
  docs/templates/github-actions/scan-and-fix/frogbot-scan-and-fix-yarn.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-dotnet.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-go.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-gradle.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-maven.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-npm.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-nuget.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pip.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-pipenv.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-poetry.yml
  docs/templates/github-actions/scan-pull-request/frogbot-scan-pr-yarn.yml
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
  starter-workflows/code-scanning/frogbot-scan-and-fix.yml
  starter-workflows/code-scanning/frogbot-scan-pr.yml
Labels: ignore for release

#269 Reduce the Scan Repositories cron frequency to one hour
  docs/install-azure-repos.md
  docs/install-bitbucket-server.md
  docs/install-github.md
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
Labels: improvement

#271 Documentation typo fix
  docs/frogbot-config.md
Labels: bug
