Repository jfrog/frogbot, pull requests merged in 2023-10, with the labels that each got.

#520 Fix golang test files
  packagehandlers/packagehandlers_test.go
  testdata/indirect-projects/go/go.mod.txt
  testdata/indirect-projects/go/go.sum.txt
  testdata/indirect-projects/go/main.go.txt
  testdata/projects/go/go.mod.txt
  testdata/projects/go/go.sum.txt
  testdata/projects/go/main.go.txt
  utils/scandetails.go
Labels: ignore for release

#521 Trim Git API endpoint slash suffix if exists
  utils/params.go
Labels: improvement

#522 Aggregate Fixes per branch
  scanrepository/scanrepository.go
  scanrepository/scanrepository_test.go
  utils/consts.go
  utils/git.go
  utils/git_test.go
Labels: improvement

#526 Fix custom templates misplacement
  .github/workflows/frogbot-scan-repository.yml
  docs/install-azure-pipelines.md
  docs/install-gitlab.md
  docs/templates/.frogbot/frogbot-config.yml
  docs/templates/github-actions/frogbot-scan-repository.yml
  docs/templates/jenkins/scan-pull-request.jenkinsfile
  docs/templates/jenkins/scan-repository.jenkinsfile
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
  schema/frogbot-schema.json
  testdata/config/frogbot-config-test-params-merge.yml
  testdata/config/frogbot-config-test-params.yml
  utils/consts.go
  utils/git.go
  utils/git_test.go
  utils/params.go
  utils/params_test.go
  utils/utils.go
Labels: bug

#527 Unreleased bug - fix dot detection in Gradle's dependency version regexp
  packagehandlers/gradlepackagehandler.go
Labels: ignore for release

#528 Fix GitHub scan repo results
  go.mod
  go.sum
  utils/utils.go
Labels: bug

#523 Add tests for SAST and Review comments
  scanpullrequest/scanpullrequest_test.go
  utils/outputwriter/outputwriter.go
  utils/outputwriter/outputwriter_test.go
  utils/outputwriter/simplifiedoutput.go
  utils/outputwriter/simplifiedoutput_test.go
  utils/outputwriter/standardoutput_test.go
  utils/reviewcomment.go
  utils/reviewcomment_test.go
  utils/testsutils.go
  utils/utils_test.go
Labels: ignore for release

#532 Bug fix in Gradle dependency regexp creation
  packagehandlers/gradlepackagehandler.go
  packagehandlers/packagehandlers_test.go
  testdata/projects/gradle/build.gradle
  testdata/projects/gradle/fixedBuildGradleForCompare.txt
  testdata/projects/gradle/innerProjectForTest/build.gradle.kts
  testdata/projects/gradle/innerProjectForTest/fixedBuildGradleKtsForCompare.txt
Labels: bug

#533 Documentation - Update SAST, Contextual Analysis and IaC images
  README.md
  images/pr-iac.png
  images/pr-sast.png
  images/pr-vuln-contextual-analysis.png
Labels: ignore for release

#535 Documentation - Replace images format from svg to png
  README.md
  images/azure-devops-icon.png
  images/azure-pipelines-icon.png
  images/bitbucket-icon.png
  images/dotnet-icon.png
  images/github-actions-icon.png
  images/github-icon.png
  images/gitlab-icon.png
  images/go-icon.png
  images/gradle-icon.png
  images/jenkins-icon.png
  images/jfrog-pipelines-icon.png
  images/maven-icon.png
  images/npm-icon.png
  images/nuget-icon.png
  images/pip-icon.png
  images/poetry-icon.png
  images/yarn-icon.png
Labels: ignore for release

#537 Avoid the deletion of existing PR comments
  .github/workflows/frogbot-scan-pull-request.yml
  docs/install-azure-pipelines.md
  docs/install-gitlab.md
  docs/templates/github-actions/frogbot-scan-pull-request.yml
  docs/templates/jenkins/scan-pull-request.jenkinsfile
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
  scanpullrequest/scanpullrequest.go
  scanpullrequest/scanpullrequest_test.go
  schema/frogbot-schema.json
  testdata/config/frogbot-config-test-unmarshal.yml
  utils/consts.go
  utils/params.go
  utils/params_test.go
  utils/reviewcomment.go
  utils/reviewcomment_test.go
Labels: new feature

#538 Retry download schema for tests
  schema/schemas_test.go
Labels: ignore for release

#540 Fix download handler on schema tests
  schema/schemas_test.go
Labels: ignore for release

#543 Add licenses to aggregateScanResults
  scanpullrequest/scanpullrequest.go
  scanpullrequest/scanpullrequest_test.go
Labels: bug

#544 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#525 Nuget multi-project support added + fixing assets files push bug
  packagehandlers/nugetpackagehandler.go
  packagehandlers/packagehandlers_test.go
  testdata/projects/dotnet/dotnet.csproj
Labels: bug

#546 Gradle- changed handler's fix function into method
  packagehandlers/gradlepackagehandler.go
  packagehandlers/packagehandlers_test.go
Labels: ignore for release

#547 PR Scanning - Prevent Frogbot from failing when comment removal fails
  scanpullrequest/scanpullrequest.go
  utils/comment.go
Labels: bug

#549 New variable for skipping extra messages
  docs/install-azure-pipelines.md
  docs/install-gitlab.md
  docs/templates/github-actions/frogbot-scan-pull-request.yml
  docs/templates/github-actions/frogbot-scan-repository.yml
  docs/templates/jenkins/scan-pull-request.jenkinsfile
  docs/templates/jenkins/scan-repository.jenkinsfile
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
  testdata/messages/summarycomment/structure/fix_mr_not_entitled.md
  testdata/messages/summarycomment/structure/fix_pr_not_entitled.md
  testdata/messages/summarycomment/structure/fix_simplified_not_entitled.md
  testdata/messages/summarycomment/structure/summary_comment_mr_issues_not_entitled.md
  testdata/messages/summarycomment/structure/summary_comment_mr_no_issues_not_entitled.md
  testdata/messages/summarycomment/structure/summary_comment_pr_issues_not_entitled.md
  testdata/messages/summarycomment/structure/summary_comment_pr_no_issues_not_entitled.md
  testdata/messages/summarycomment/structure/summary_comment_simplified_issues_not_entitled.md
  testdata/messages/summarycomment/structure/summary_comment_simplified_no_issues_not_entitled.md
  utils/consts.go
  utils/outputwriter/outputcontent.go
  utils/outputwriter/outputcontent_test.go
  utils/outputwriter/outputwriter.go
  utils/outputwriter/simplifiedoutput.go
  utils/outputwriter/standardoutput.go
  utils/params.go
  utils/params_test.go
Labels: improvement

#554 Update build-info-go to v1.9.14
  go.mod
  go.sum
  packagehandlers/packagehandlers_test.go
Labels: ignore for release

#556 New variable for adding pull request comment title
  docs/install-azure-pipelines.md
  docs/install-gitlab.md
  docs/templates/.frogbot/frogbot-config.yml
  docs/templates/github-actions/frogbot-scan-pull-request.yml
  docs/templates/jenkins/scan-pull-request.jenkinsfile
  docs/templates/jfrog-pipelines/pipelines-dotnet.yml
  docs/templates/jfrog-pipelines/pipelines-go.yml
  docs/templates/jfrog-pipelines/pipelines-gradle.yml
  docs/templates/jfrog-pipelines/pipelines-maven.yml
  docs/templates/jfrog-pipelines/pipelines-npm.yml
  docs/templates/jfrog-pipelines/pipelines-pip.yml
  docs/templates/jfrog-pipelines/pipelines-pipenv.yml
  docs/templates/jfrog-pipelines/pipelines-poetry.yml
  docs/templates/jfrog-pipelines/pipelines-yarn2.yml
  schema/frogbot-schema.json
  testdata/config/frogbot-config-test-params.yml
  testdata/messages/summarycomment/structure/summary_comment_mr_issues_entitled_with_title.md
  testdata/messages/summarycomment/structure/summary_comment_pr_issues_not_entitled_with_title.md
  testdata/messages/summarycomment/structure/summary_comment_simplified_issues_entitled_with_title.md
  utils/consts.go
  utils/outputwriter/outputcontent.go
  utils/outputwriter/outputcontent_test.go
  utils/outputwriter/outputwriter.go
  utils/outputwriter/simplifiedoutput.go
  utils/outputwriter/standardoutput.go
  utils/params.go
  utils/params_test.go
Labels: new feature

#551 NPM scan repository pushes node_modules into PR fix
  packagehandlers/npmpackagehandler.go
Labels: bug

#561 Blocking NPM auto-install in frogbot + Passing forward install command args
  go.mod
  go.sum
  utils/scandetails.go
Labels: improvement
