Repository jfrog/frogbot, pull requests merged in 2024-09, with the labels that each got.

#744 Updating versions and fix breaks
  go.mod
  go.sum
  scanrepository/scanrepository.go
Labels: ignore for release

#746 Fix breaking changes after security PR
  go.mod
  go.sum
  utils/utils.go
  utils/utils_test.go
Labels: ignore for release

#740 Added centralized config resolution and utilization for Scan-PR flow
  go.mod
  go.sum
  scanpullrequest/scanpullrequest.go
  scanpullrequest/scanpullrequest_test.go
  testdata/configprofile/configProfileExample.json
  utils/consts.go
  utils/params.go
  utils/params_test.go
  utils/scandetails.go
  utils/testsutils.go
Labels: ignore for release

#747 Upload result to GHAS only if JAS entitled
  scanrepository/scanrepository.go
Labels: improvement

#748 Use sast fingerprint when comparing source and target scan results
  go.mod
  go.sum
  integrationutils.go
  scanpullrequest/scanpullrequest.go
Labels: improvement

#750 Update dependencies
  go.mod
  go.sum
Labels: improvement

#751 Add option to skip auto fix in Frogbot scan repository
  scanrepository/scanrepository.go
  utils/consts.go
  utils/params.go
  utils/params_test.go
Labels: improvement

#749 Add technology to audit params if provided by user through 'install' command
  go.mod
  go.sum
  utils/params.go
  utils/scandetails.go
Labels: bug

#752 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#753 Remove "fix log" in detection only mode
  scanrepository/scanrepository.go
Labels: ignore for release

#756 Update dependencies
  go.mod
  go.sum
  scanpullrequest/scanpullrequest_test.go
Labels: improvement

#757 Update Dependencies
  go.mod
  go.sum
  utils/utils.go
Labels: improvement
