Repository jfrog/frogbot, pull requests merged in 2024-02, with the labels that each got.

#631 Scan fails upon empty PR push
  scanrepository/scanrepository.go
  utils/utils.go
Labels: bug

#638 Fix changes at Mvn handler
  go.mod
  go.sum
  packagehandlers/mavenpackagehandler.go
  packagehandlers/packagehandlers_test.go
Labels: ignore for release

#640 Turn Gradle daemon off for tests
  .github/workflows/test.yml
Labels: ignore for release

#633 Create multi scan id before running audit command
  go.mod
  go.sum
  scanrepository/scanrepository.go
  utils/scandetails.go
Labels: improvement

#637 Keep local changes before moving to a new branch optimization
  integrationutils.go
  scanrepository/scanrepository.go
  utils/git.go
  utils/git_test.go
  utils/scanrepository.go
Labels: ignore for release

#639 Enable resolving vulnerable dependencies fixes from an Artifactory server for Golang projects
  go.mod
  go.sum
  packagehandlers/gopackagehandler.go
Labels: improvement

#643 Update dependencies for release
  go.mod
  go.sum
Labels: ignore for release

#644 Update Go version to 1.21
  .github/workflows/analysis.yml
  .github/workflows/test.yml
  go.mod
  go.sum
Labels: improvement

#645 Update Jfrog dependencies
  go.mod
  go.sum
Labels: improvement
