Repository jfrog/frogbot, pull requests merged in 2024-04, with the labels that each got.

#672 Adds Severity Field for Licenses Violations for Pull Request Scans
  images/violated-licenses.png
  testdata/messages/summarycomment/license/license_violation_simplified.md
  testdata/messages/summarycomment/license/license_violation_standard.md
  utils/outputwriter/outputcontent.go
  utils/outputwriter/outputcontent_test.go
Labels: bug

#673 Adding error logs report to Coralogix
  commands.go
  go.mod
  go.sum
  integrationutils.go
  scanrepository/scanrepository.go
  utils/scandetails.go
Labels: improvement

#676 Adding analytics reports to Frogbot flows
  go.mod
  go.sum
  scanpullrequest/scanpullrequest.go
  scanrepository/scanrepository.go
  utils/analytics.go
  utils/analytics_test.go
  utils/consts.go
  utils/issuescollection.go
  utils/issuescollection_test.go
Labels: improvement

#686 Readme fix
  README.md
Labels: ignore for release

#681 Fix panicing test
  integrationutils.go
  scanrepository/scanrepository_test.go
Labels: ignore for release

#689 Fill xsc version field by calling xscVersion endpoint
  scanrepository/scanrepository.go
Labels: bug
