Repository jfrog/frogbot, pull requests merged in 2024-12, with the labels that each got.

#793 Show secrets detected at PR scan
  testdata/messages/reviewcomment/secrets/secret_review_content_no_ca_simplified.md
  testdata/messages/reviewcomment/secrets/secret_review_content_no_ca_standard.md
  testdata/messages/reviewcomment/secrets/secret_review_content_simplified.md
  testdata/messages/reviewcomment/secrets/secret_review_content_standard.md
  utils/comment.go
  utils/comment_test.go
  utils/consts.go
  utils/outputwriter/outputcontent.go
  utils/outputwriter/outputcontent_test.go
  utils/params.go
Labels: improvement

#801 Fix breaks in Frogbot according to recent cli-security changes
  go.mod
  go.sum
  scanpullrequest/scanallpullrequests_test.go
  scanpullrequest/scanpullrequest_test.go
  scanrepository/scanmultiplerepositories_test.go
  scanrepository/scanrepository_test.go
  utils/params.go
Labels: ignore for release

#802 Fix resolve common ancestor hash when revision not found
  go.mod
  go.sum
  scanpullrequest/scanpullrequest.go
  testdata/resources/bitbucket_server_home.zip
  utils/git.go
Labels: bug

#803 Add Mono download to Ubuntu test env
  .github/workflows/test.yml
Labels: ignore for release

#805 Fix issue in test
  testdata/scanrepository/cmd/partial-results-enabled/inner-project/package.json
Labels: ignore for release

#806 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#797 Config profile with repo API integration
  .github/workflows/test.yml
  go.mod
  go.sum
  scanpullrequest/scanpullrequest.go
  scanrepository/scanrepository.go
  utils/consts.go
  utils/params.go
  utils/params_test.go
  utils/testsutils.go
  utils/utils.go
Labels: ignore for release

#807 Add option to control the Pnpm dependencies tree depth
  utils/consts.go
  utils/params.go
  utils/scandetails.go
Labels: improvement

#809 Skip comment generation on PR success if needed
  scanpullrequest/scanallpullrequests_test.go
  utils/comment.go
  utils/consts.go
  utils/params.go
  utils/params_test.go
Labels: improvement
