Repository jfrog/frogbot, pull requests merged in 2024-03, with the labels that each got.

#632 Rephrasing no errors found message
  resources/v2/noVulnerabilityBannerMR.png
  resources/v2/noVulnerabilityBannerPR.png
  testdata/messages/summarycomment/structure/summary_comment_no_issues_mr_entitled.md
  testdata/messages/summarycomment/structure/summary_comment_no_issues_mr_not_entitled.md
  testdata/messages/summarycomment/structure/summary_comment_no_issues_pr_entitled.md
  testdata/messages/summarycomment/structure/summary_comment_no_issues_pr_entitled_with_title.md
  testdata/messages/summarycomment/structure/summary_comment_no_issues_pr_not_entitled.md
  testdata/messages/summarycomment/structure/summary_comment_no_issues_pr_not_entitled_with_title.md
  testdata/messages/summarycomment/structure/summary_comment_no_issues_simplified_entitled.md
  testdata/messages/summarycomment/structure/summary_comment_no_issues_simplified_not_entitled.md
  testdata/messages/summarycomment/structure/summary_comment_no_issues_simplified_not_entitled_with_title.md
  utils/outputwriter/icons.go
  utils/outputwriter/icons_test.go
  utils/outputwriter/simplifiedoutput_test.go
  utils/outputwriter/standardoutput_test.go
Labels: ignore for release

#658 Fix comments removal & scan-all-PRs iteration bugs
  scanpullrequest/scanallpullrequests.go
  utils/comment.go
Labels: ignore for release

#656 Add Pnpm support
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/test.yml
  go.mod
  go.sum
  packagehandlers/commonpackagehandler.go
  packagehandlers/gradlepackagehandler.go
  packagehandlers/mavenpackagehandler.go
  packagehandlers/nugetpackagehandler.go
  packagehandlers/packagehandlers_test.go
  packagehandlers/pnpmpackagehandler.go
Labels: new feature

#669 Updating UpdateDependency test for all package managers + tests fixes
  go.mod
  packagehandlers/packagehandlers_test.go
Labels: ignore for release

#671 Update dependencies
  go.mod
  go.sum
Labels: improvement
