Repository jfrog/frogbot, pull requests merged in 2024-01, with the labels that each got.

#611 Update vulnerable dependencies
  go.mod
  go.sum
Labels: dependencies

#614 Update maven-dep-tree to v1.1.0
  go.mod
  go.sum
Labels: improvement

#617 Improvement for recursive scan detection
  go.mod
  go.sum
  utils/params.go
  utils/params_test.go
  utils/scandetails.go
Labels: improvement

#616 Use Jfrog-CLI-Security
  go.mod
  go.sum
  packagehandlers/mavenpackagehandler.go
  packagehandlers/packagehandlers_test.go
  scanpullrequest/scanpullrequest.go
  scanpullrequest/scanpullrequest_test.go
  scanrepository/scanrepository.go
  scanrepository/scanrepository_test.go
  utils/comment.go
  utils/comment_test.go
  utils/email.go
  utils/email_test.go
  utils/issuescollection.go
  utils/outputwriter/outputcontent.go
  utils/outputwriter/outputcontent_test.go
  utils/params.go
  utils/scandetails.go
  utils/utils.go
  utils/utils_test.go
Labels: ignore for release

#625 Fix missing v2 tag on go module name - github.com/jfrog/frogbot/v2
  .github/workflows/test.yml
  azure_test.go
  bitbucket_server_test.go
  commands.go
  github_test.go
  gitlab_test.go
  go.mod
  integrationutils.go
  main.go
  main_test.go
  packagehandlers/commonpackagehandler.go
  packagehandlers/gopackagehandler.go
  packagehandlers/gradlepackagehandler.go
  packagehandlers/mavenpackagehandler.go
  packagehandlers/npmpackagehandler.go
  packagehandlers/nugetpackagehandler.go
  packagehandlers/packagehandlers_test.go
  packagehandlers/pythonpackagehandler.go
  packagehandlers/unsupportedpackagehandler.go
  packagehandlers/yarnpackagehandler.go
  scanpullrequest/scanallpullrequests.go
  scanpullrequest/scanallpullrequests_test.go
  scanpullrequest/scanpullrequest.go
  scanpullrequest/scanpullrequest_test.go
  scanrepository/scanmultiplerepositories.go
  scanrepository/scanmultiplerepositories_test.go
  scanrepository/scanrepository.go
  scanrepository/scanrepository_test.go
  utils/comment.go
  utils/comment_test.go
  utils/consts.go
  utils/email.go
  utils/email_test.go
  utils/params.go
  utils/utils.go
  utils/utils_test.go
Labels: bug

#622 NPM: Enable dependencies resolution from Artifactory in scan-and-fix
  go.mod
  go.sum
  packagehandlers/commonpackagehandler.go
  packagehandlers/npmpackagehandler.go
  packagehandlers/packagehandlers_test.go
  packagehandlers/unsupportedpackagehandler.go
Labels: improvement

#626 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#627 Fix version path in release
  release/buildAndUpload.sh
Labels: ignore for release

#630 Update dependencies
  go.mod
  go.sum
Labels: bug
