Repository jfrog/frogbot, pull requests merged in 2024-10, with the labels that each got.

#765 Update Dependencies
  .github/workflows/cla.yml
  go.mod
  go.sum
Labels: improvement

#758 Add skip-auto-install capability in Scan-Repository flow
  go.mod
  go.sum
  scanpullrequest/scanpullrequest.go
  scanrepository/scanrepository.go
  utils/consts.go
  utils/params.go
  utils/scandetails.go
Labels: new feature

#762 Enable allow-partial-results to ScanRepository
  go.mod
  go.sum
  scanrepository/scanrepository.go
  scanrepository/scanrepository_test.go
  testdata/scanrepository/cmd/partial-results-enabled/.frogbot/frogbot-config.yml
  testdata/scanrepository/cmd/partial-results-enabled/README.md
  testdata/scanrepository/cmd/partial-results-enabled/inner-project/package.json
  testdata/scanrepository/cmd/partial-results-enabled/package-lock.json
  testdata/scanrepository/cmd/partial-results-enabled/package.json
  utils/consts.go
  utils/params.go
  utils/scandetails.go
  utils/utils.go
Labels: new feature

#766 Update dependencies
  go.mod
  go.sum
Labels: ignore for release

#767 Enable using local repository instead cloning a remote repo - ScanRepository
  azure_test.go
  bitbucket_server_test.go
  github_test.go
  gitlab_test.go
  integrationutils.go
  scanrepository/scanrepository.go
  utils/consts.go
  utils/git.go
  utils/params.go
Labels: new feature

#772 Clear new locally created files before pushing a fix
  scanrepository/scanrepository.go
  scanrepository/scanrepository_test.go
  utils/git.go
Labels: improvement

#773 update dependencies for release 2.23.0
  go.mod
  go.sum
Labels: ignore for release

#776 Add option to disable Jas scans
  scanpullrequest/scanpullrequest.go
  scanrepository/scanrepository.go
  utils/consts.go
  utils/params.go
  utils/params_test.go
  utils/scandetails.go
Labels: improvement

#763 Scan PR - Add option to scan source and most common ancestor target c…
  scanpullrequest/scanpullrequest.go
  utils/consts.go
  utils/git.go
  utils/params.go
Labels: improvement
