Repository jfrog/frogbot, pull requests merged in 2025-09, with the labels that each got.

#911 Fix for nugget tests in mac and ubuntu
  .github/workflows/test.yml
Labels: ignore for release

#913 Update dependencies
  go.mod
  go.sum
  utils/scandetails.go
Labels: ignore for release

#882 Adding a working tree isClean checkup before sending a commit request
  integrationutils.go
  scanrepository/scanrepository.go
  utils/git.go
  utils/utils.go
Labels: bug

#916 Improve Params fetching conditions
  utils/params.go
Labels: ignore for release

#917 Update dependencies for 2.28.0
  go.mod
  go.sum
Labels: ignore for release

#918 Replace vulnerable version of replace github.com/ulikunitz/xz from version v0.5.14 to v0.5.15
  go.mod
  go.sum
Labels: ignore for release

#923 Added the origin field for custom scanner
  testdata/messages/reviewcomment/secrets/secret_review_content_no_ca_simplified.md
  testdata/messages/reviewcomment/secrets/secret_review_content_no_ca_standard.md
  testdata/messages/reviewcomment/secrets/secret_review_content_simplified.md
  testdata/messages/reviewcomment/secrets/secret_review_content_standard.md
  testdata/messages/reviewcomment/secrets/secret_violation_review_content_simplified.md
  testdata/messages/reviewcomment/secrets/secret_violation_review_content_standard.md
  utils/outputwriter/outputcontent.go
  utils/outputwriter/outputcontent_test.go
Labels: improvement
