Repository jfrog/frogbot, pull requests merged in 2025-04, with the labels that each got.

#851 Fix OIDC broken test
  .github/workflows/oidc-test.yml
Labels: bug

#834 Restricting usage in ConfigProfile with Xray version prior to 3.117.0
  go.mod
  go.sum
  testdata/configprofile/configProfileExample.json
  utils/params.go
  utils/params_test.go
  utils/scandetails.go
  utils/testsutils.go
Labels: new feature

#848 Make sure no attempts to create empty comment for PR Scan on split
  utils/outputwriter/outputcontent_test.go
  utils/outputwriter/outputwriter.go
Labels: bug

#855 Add debug logs to indicate scanned branches in scan-repo
  scanrepository/scanrepository.go
Labels: ignore for release

#856 Add Author attribute for test mocks
  go.mod
  go.sum
  scanpullrequest/scanallpullrequests_test.go
  scanrepository/scanrepository_test.go
  testdata/scanpullrequest/expectedPullRequestDetailsResponse.json
Labels: ignore for release

#857 Update dependencies for 2.26.0
  go.mod
  go.sum
Labels: ignore for release

#859 Updated the security issues found log to include the JF_FAIL flag
  scanpullrequest/scanpullrequest.go
Labels: improvement
