Repository jfrog/frogbot, pull requests merged in 2025-01, with the labels that each got.

#813 Don't access ScanStatus on nil
  scanpullrequest/scanpullrequest.go
Labels: bug

#815 Update Dependencies
  go.mod
  go.sum
Labels: improvement

#812 Adjustments to recent changes in analytics report
  go.mod
  go.sum
  scanpullrequest/scanpullrequest.go
  scanrepository/scanrepository.go
Labels: ignore for release
